name: nabat_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - liblapack==3.9.0=16_osxarm64_openblas
  - hdf5==1.12.1=nompi_hd9dbc9e_104
  - libzlib==1.2.13=h03a7124_4
  - libxcb==1.13=h9b22ae9_1004
  - pip==22.3.1=pyhd8ed1ab_0
  - unicodedata2==15.0.0=py38hb991d35_0
  - pillow==9.2.0=py38hf86a106_3
  - traitlets==5.5.0=pyhd8ed1ab_0
  - comm==0.1.0=pyhd8ed1ab_0
  - libopenblas==0.3.21=openmp_hc731615_3
  - jpeg==9e=he4db4b2_2
  - libbrotlienc==1.0.9=h1a8c8d9_8
  - munkres==1.1.4=pyh9f0ad1d_0
  - fonttools==4.38.0=py38hb991d35_1
  - krb5==1.19.3=he492e65_0
  - importlib-metadata==5.0.0=pyha770c72_1
  - zeromq==4.3.4=hbdafb3b_1
  - bzip2==1.0.8=h3422bc3_4
  - six==1.16.0=pyh6c4a22f_0
  - python-fastjsonschema==2.16.2=pyhd8ed1ab_0
  - libssh2==1.10.0=h7a5bd25_3
  - python-dateutil==2.8.2=pyhd8ed1ab_0
  - libffi==3.4.2=h3422bc3_5
  - ipykernel
  - matplotlib-base==3.6.2=py38hbbe890c_0
  - packaging==21.3=pyhd8ed1ab_0
  - brotli-bin==1.0.9=h1a8c8d9_8
  - pickleshare==0.7.5=py_1003
  - pkgutil-resolve-name==1.3.10=pyhd8ed1ab_0
  - ptyprocess==0.7.0=pyhd3deb0d_0
  - libprotobuf==3.19.4=hccf11d3_0
  - libedit==3.1.20191231=hc8eb9b7_2
  - ipython==8.6.0=pyhd1c38e8_1
  - libdeflate==1.14=h1a8c8d9_0
  - nbformat==5.7.0=pyhd8ed1ab_0
  - pyrsistent==0.19.2=py38hb991d35_0
  - pure_eval==0.2.2=pyhd8ed1ab_0
  - pthread-stubs==0.4=h27ca646_1001
  - h5py==3.6.0=nompi_py38hacf61ce_100
  - lcms2==2.14=h8193b64_0
  - decorator==5.1.1=pyhd8ed1ab_0
  - libgfortran5==11.3.0=hdaf2cc0_26
  - xorg-libxau==1.0.9=h27ca646_0
  - jedi==0.18.2=pyhd8ed1ab_0
  - pytz==2022.6=pyhd8ed1ab_0
  - nest-asyncio==1.5.6=pyhd8ed1ab_0
  - xz==5.2.6=h57fd34a_0
  - openssl
  - prompt-toolkit==3.0.33=pyha770c72_0
  - jupyterlab_widgets==3.0.3=pyhd8ed1ab_0
  - typing_extensions==4.4.0=pyha770c72_0
  - debugpy==1.6.3=py38h2b1e499_1
  - importlib_resources==5.10.0=pyhd8ed1ab_0
  - zlib==1.2.13=h03a7124_4
  - appnope==0.1.3=pyhd8ed1ab_0
  - ca-certificates
  - libgfortran==5.0.0=11_3_0_hd922786_26
  - brotli==1.0.9=h1a8c8d9_8
  - libpng==1.6.39=h76d750c_0
  - attrs==22.1.0=pyh71513ae_1
  - lerc==4.0.0=h9a09cb3_0
  - libblas==3.9.0=16_osxarm64_openblas
  - libbrotlicommon==1.0.9=h1a8c8d9_8
  - libev==4.33=h642e427_1
  - tk==8.6.12=he1e0b03_0
  - backports==1.0=py_2
  - libbrotlidec==1.0.9=h1a8c8d9_8
  - readline==8.1.2=h46ed386_0
  - backcall==0.2.0=pyh9f0ad1d_0
  - pexpect==4.8.0=pyh1a96a4e_2
  - libnghttp2==1.47.0=h519802c_1
  - libsqlite==3.40.0=h76d750c_0
  - matplotlib-inline==0.1.6=pyhd8ed1ab_0
  - grpcio==1.46.3=py38h1ef021a_0
  - libcblas==3.9.0=16_osxarm64_openblas
  - tensorflow-deps==2.10.0=0
  - zstd==1.5.2=h8128057_4
  - asttokens==2.1.0=pyhd8ed1ab_0
  - executing==1.2.0=pyhd8ed1ab_0
  - stack_data==0.6.1=pyhd8ed1ab_0
  - jupyter_core==5.0.0=py38h10201cd_0
  - openjpeg==2.5.0=h5d4e404_1
  - setuptools
  - libtiff==4.4.0=hfa0b094_4
  - pandas==1.5.2=py38h61dac83_0
  - tornado==6.2=py38hb991d35_1
  - platformdirs==2.5.2=pyhd8ed1ab_1
  - widgetsnbextension==4.0.3=pyhd8ed1ab_0
  - jupyter_client==7.4.7=pyhd8ed1ab_0
  - libcurl==7.86.0=h1c293e1_1
  - pyparsing==3.0.9=pyhd8ed1ab_0
  - xorg-libxdmcp==1.1.3=h27ca646_0
  - pyzmq==24.0.1=py38hb72be9f_1
  - ncurses==6.3=h07bb92c_1
  - wcwidth==0.2.5=pyh9f0ad1d_2
  - kiwisolver==1.4.4=py38h9dc3d6a_1
  - contourpy==1.0.6=py38h9dc3d6a_0
  - entrypoints==0.4=pyhd8ed1ab_0
  - zipp==3.10.0=pyhd8ed1ab_0
  - libwebp-base==1.2.4=h57fd34a_0
  - backports.functools_lru_cache==1.6.4=pyhd8ed1ab_0
  - ipywidgets==8.0.2=pyhd8ed1ab_1
  - scipy==1.9.3=py38h7b4f323_2
  - llvm-openmp==15.0.5=h7cfbb63_0
  - freetype==2.12.1=hd633e50_0
  - pygments==2.13.0=pyhd8ed1ab_0
  - cycler==0.11.0=pyhd8ed1ab_0
  - libcxx==14.0.6=h2692d47_0
  - cached-property==1.5.2=hd8ed1ab_1
  - matplotlib==3.6.2=py38h150bfb4_0
  - python_abi==3.8=3_cp38
  - libsodium==1.0.18=h27ca646_1
  - cached_property==1.5.2=pyha770c72_1
  - c-ares==1.18.1=h3422bc3_0
  - jsonschema==4.17.0=pyhd8ed1ab_0
  - python==3.8.15=h3ba56d0_0_cpython
  - parso==0.8.3=pyhd8ed1ab_0
  - wheel==0.38.4=pyhd8ed1ab_0
  - psutil==5.9.4=py38hb991d35_0
  - librosa
prefix: /Users/adityakrishna/miniforge3/envs/nabat_ml
